on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: codeberg-small   # or codeberg-medium / codeberg-tiny
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Codeberg Pages
        uses: https://code.forgejo.org/actions/git-pages@v2
        with:
          site: "http://www.biosignalsystems.com"
          token: ${{ forge.token }}
          source: "."
